# Generated by Django 2.2.7 on 2019-11-12 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
