# Generated by Django 2.2.7 on 2019-11-12 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='pet_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Questionaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.CharField(max_length=255)),
                ('answer_1', models.CharField(max_length=255)),
                ('question_2', models.CharField(max_length=255)),
                ('answer_2', models.CharField(max_length=255)),
                ('question_3', models.CharField(max_length=255)),
                ('answer_3', models.CharField(max_length=255)),
                ('question_4', models.CharField(max_length=255)),
                ('answer_4', models.CharField(max_length=255)),
                ('question_5', models.CharField(max_length=255)),
                ('answer_5', models.CharField(max_length=255)),
                ('question_6', models.CharField(max_length=255)),
                ('answer_6', models.CharField(max_length=255)),
                ('question_7', models.CharField(max_length=255)),
                ('answer_7', models.CharField(max_length=255)),
                ('question_8', models.CharField(max_length=255)),
                ('answer_8', models.CharField(max_length=255)),
                ('question_9', models.CharField(max_length=255)),
                ('answer_9', models.CharField(max_length=255)),
                ('question_10', models.CharField(max_length=255)),
                ('answer_10', models.CharField(max_length=255)),
                ('question_11', models.CharField(max_length=255)),
                ('answer_11', models.CharField(max_length=255)),
                ('question_12', models.CharField(max_length=255)),
                ('answer_12', models.CharField(max_length=255)),
                ('question_13', models.CharField(max_length=255)),
                ('answer_13', models.CharField(max_length=255)),
                ('question_14', models.CharField(max_length=255)),
                ('answer_14', models.CharField(max_length=255)),
                ('question_15', models.CharField(max_length=255)),
                ('answer_15', models.CharField(max_length=255)),
                ('question_16', models.CharField(max_length=255)),
                ('answer_16', models.CharField(max_length=255)),
                ('question_17', models.CharField(max_length=255)),
                ('answer_17', models.CharField(max_length=255)),
                ('question_18', models.CharField(max_length=255)),
                ('answer_18', models.CharField(max_length=255)),
                ('question_19', models.CharField(max_length=255)),
                ('answer_19', models.CharField(max_length=255)),
                ('question_20', models.CharField(max_length=255)),
                ('answer_20', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('user', models.CharField(max_length=50)),
                ('address_line_1', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.IntegerField()),
                ('user_age', models.IntegerField()),
                ('looking_for', models.CharField(max_length=50)),
                ('pet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='profiles.Pet')),
                ('questionaire_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='profiles.Questionaire')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionaire_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='profiles.Questionaire')),
                ('user_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='profiles.User_Profile')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='profiles.pet_profile'),
        ),
        migrations.AddField(
            model_name='pet',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='profiles.User'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='profiles.User')),
            ],
        ),
    ]
