# Generated by Django 2.2.7 on 2019-11-13 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20191113_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='profiles.User_Profile'),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='answer_1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.User_Profile'),
        ),
    ]
