# Generated by Django 2.2.7 on 2019-11-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20191113_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet_profile',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
