# Generated by Django 2.2.6 on 2019-11-13 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_pet_profile_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pet_Profile',
            new_name='Pet',
        ),
        migrations.RenameModel(
            old_name='User_Profile',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='user_profile',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='questionaire',
            old_name='user_profile',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='pet_profile',
            new_name='pet',
        ),
    ]
