# Generated by Django 2.2.6 on 2019-11-13 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20191113_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='user',
            field=models.ManyToManyField(related_name='pets', to='profiles.User'),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionaires', to='profiles.User'),
        ),
    ]
